services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    image: 'rabbitmq:3-management'
    networks:
      - messageApp
  
  # mssqlserver:
  #   image: 'mcr.microsoft.com/mssql/server:2022-latest'
  #   container_name: mssqlserver
  #   environment:
  #       - ACCEPT_EULA=Y
  #       - SA_PASSWORD=msSQL@123
  #   ports:
  #       - '1433:1433'
  #   networks:
  #     - messageApp

networks:
  messageApp:
    driver: bridge
